require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - "assets/**/*"
    - "bin/**/*"
    - "db/schema.rb"
    - "log/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - "app/admin/**/*"
# Documentational:
#   Enabled: false